trigger: 
 branches:
   include:
     - main

pool:
  name: my-pool
  demands:
  - Agent.Name -equals infra-agent


stages:
  - stage: Build
    displayName: Build Application
    jobs:
      - job: Build_job
        displayName: Maven Build
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'clean package'
            publishJUnitResults: false
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false

        - publish: target/JavaLoginShowcase-1.0.0.war
          displayName: Publish WAR Artifact
          artifact: war

        

  - stage: Test
    displayName: Test & Publish Artifact
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Test_Job
        displayName: Run Unit Test
        steps:
        - task: Maven@4
          inputs:
            mavenPomFile: 'pom.xml'
            goals: 'test'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false


  - stage: Deploy
    displayName: Deploy to TomCat Server
    dependsOn: Test
    condition: succeeded()
    jobs:
    - job: deploy
      displayName: Deploy WAR
      steps:
        - download: current
          artifact: war

        - script: |
            TOMCAT_WEBAPPS="/opt/tomcat/webapps"

            echo "Stopping Tomcat"
            sudo systemctl stop tomcat9

            echo "Cleaning old deployment..."
            sudo rm -rf $TOMCAT_WEBAPPS/ROOT*

            echo "Deploying new WAR..."
            sudo cp $(Pipeline.Workspace)/war/*.war $TOMCAT_WEBAPPS/ROOT.war

            echo "Starting Tomcat..."
            sudo systemctl start tomcat9
          displayName: Tomcat Deploy
